ALL_COMPETENCES = [
    {"id": 1, "name": "Colaboramos de verdade"},
    {"id": 2, "name": "Nosso compromisso é coletivo"},
    {"id": 4, "name": "Focamos no cliente"},
    {"id": 3, "name": "Vamos direto ao ponto"},
    {"id": 7, "name": "Protagonizamos o futuro"},
    {"id": 5, "name": "Entregamos valor de ponta a ponta"},
    {"id": 8, "name": "Tomamos a iniciativa"},
    {"id": 6, "name": "Decidimos com contexto"},
    {"id": 9, "name": "Entrega soluções técnicas"},
    {"id": 10, "name": "Aplicabilidade de novos conhecimentos técnicos"},
    {"id": 11, "name": "Linguagem de Programação [Java, Go, Kotlin, C#, Python, Swift, etc ]"},
    {"id": 12, "name": "Algoritmos e Estrutura de Dados"},
    {"id": 13, "name": "Fluxo de trabalho/Workflow"},
    {"id": 14, "name": "Pipeline CI/CD"},
    {"id": 15, "name": "APIs"},
    {"id": 16, "name": "Segurança"},
    {"id": 17, "name": "Arquitetura de soluções"},
    {"id": 18, "name": "Redes (VPC, CDN, DNS, etc)"},
    {"id": 19, "name": "Infra / IaC (Terraform, CloudFormation, etc)"},
    {"id": 23, "name": "StackSpot AI"},
    {"id": 25, "name": "Computing services (EC2, ECS, EKS, Fargate, Lambda, etc)"},
    {"id": 26, "name": "Observabilidade e Monitoramento"},
    {"id": 27, "name": "SQL / noSQL"},
    {"id": 28, "name": "Cache"},
    {"id": 29, "name": "Inteligencia Artificial"},
    {"id": 39, "name": "Javascript Runtime (Hoisting, Eveent Loop, Coerção...)"},
    {"id": 40, "name": "Arquitetura de Solução"},
    {"id": 41, "name": "Qualidade"},
    {"id": 42, "name": "Web Rendering Strategies"},
    {"id": 43, "name": "Building"},
    {"id": 44, "name": "Microfrontend"},
    {"id": 45, "name": "AWS e Infraestrutura"},
    {"id": 46, "name": "Conhecimentos em Kotlin e boas práticas"},
    {"id": 47, "name": "Integração com APIs"},
    {"id": 48, "name": "Layouts e Navegação"},
    {"id": 49, "name": "Ciclo de vida"},
    {"id": 50, "name": "Testes Automatizados"},
    {"id": 51, "name": "Gerenciamento de Dependência"},
    {"id": 52, "name": "Log, Debug, Performance"},
    {"id": 53, "name": "Versionamento"},
    {"id": 54, "name": "Code Review"},
    {"id": 55, "name": "Acessibilidade"},
    {"id": 56, "name": "Stackspot AI"},
    {"id": 57, "name": "Inteligência Artificial"},
    {"id": 58, "name": "Injeção de Dependência"},
    {"id": 59, "name": "Arquitetura"},
    {"id": 60, "name": "Jetpack/Features"},
    {"id": 61, "name": "Uso e criação de Libs"},
    {"id": 62, "name": "CI/CD"},
    {"id": 63, "name": "Backend/BFF"},
    {"id": 64, "name": "Algoritmo e Estrutura de Dados"},
    {"id": 65, "name": "Fundamentos AWS"},
    {"id": 66, "name": "Conhecimento em linguagem de programação Python e Spark"},
    {"id": 67, "name": "Conhecimento em SQL"},
    {"id": 68, "name": "Conhecimento em serviços cloud para big data"},
    {"id": 69, "name": "Conhecimento em Git e Terraform"},
    {"id": 70, "name": "Conhecimento básico de API/HTTP/REST"},
    {"id": 71, "name": "Conhecimento de arquitetura de dados (Data Lake, Mesh, kappa, lambda, modelagem, etc)"},
    {"id": 72, "name": "Bancos de dados"},
    {"id": 73, "name": "Conhecimento de Governança de Dados (Data Lineage, LGPD, GDPR., Ciclo de Vida)"},
    {"id": 74, "name": "Conhecimento em framework de processamento distribuído"},
    {"id": 75, "name": "Layout"},
    {"id": 76, "name": "API"},
    {"id": 77, "name": "Gerenciamento de memória"},
    {"id": 78, "name": "Conhecimentos Básicos"},
    {"id": 79, "name": "Controle de Versão"},
    {"id": 80, "name": "Codificação"},
    {"id": 81, "name": "Cloud"},
    {"id": 82, "name": "Banco de dados"},
    {"id": 83, "name": "Arquitetura de Sistemas"},
    {"id": 84, "name": "Infraestrutura e Cloud"},
    {"id": 85, "name": "Segurança da Informação"},
    {"id": 86, "name": "DevOps e Observabilidade"},
    {"id": 87, "name": "Gestão de Dados"},
    {"id": 88, "name": "Linguagens e Frameworks"},
    {"id": 89, "name": "Qualidade e Performance"},
    {"id": 90, "name": "Gestão de Ciclo de Vida de Software"},
    {"id": 91, "name": "Inteligência artificial"},
    {"id": 92, "name": "Gestão de Carreiras"},
    {"id": 93, "name": "Gestão Orçamentária e de Indicadores"},
    {"id": 94, "name": "Gestão de OKRs"},
    {"id": 95, "name": "Conceitos gerais de Testes de Software"},
    {"id": 96, "name": "Automação de Testes e Frameworks"},
    {"id": 97, "name": "Boas Práticas de programação e automação"},
    {"id": 98, "name": "Identificação de problemas, CI/CD e Versionamento"},
    {"id": 99, "name": "QA \"ágil\""},
    {"id": 100, "name": "Monitoring, Observability"},
    {"id": 101, "name": "Software Lifecycle"},
    {"id": 102, "name": "Enterprise / Internal Development Platform"},
    {"id": 103, "name": "GitOps & IaC automation"},
    {"id": 104, "name": "Bancos de Dados"},
    {"id": 105, "name": "Redes"},
    {"id": 106, "name": "Linux"},
    {"id": 107, "name": "Cost Optimization"},
    {"id": 108, "name": "Service Mesh"},
    {"id": 109, "name": "KNOWLEDGE & EXPERIENCE"},
    {"id": 110, "name": "BIG PICTURE THINKING"},
    {"id": 111, "name": "EXECUÇÃO E COMPLEXIDADE DE TRABALHO"},
    {"id": 112, "name": "NOTORIEDADE E INFLUÊNCIA POSITIVA"},
    {"id": 113, "name": "IMPACTO"},
    {"id": 114, "name": "SUPERVISÃO / MENTORIA"},
    {"id": 115, "name": "Conhecimentos fundamentais da área"},
    {"id": 116, "name": "Ferramentas e Tecnologias"},
    {"id": 117, "name": "Negócio e Contexto Organizacional"},
    {"id": 118, "name": "Comunicação e Influência"},
    {"id": 119, "name": "Gestão de Projetos e Processos"},
    {"id": 120, "name": "Gestão de Risco e Qualidade"}
]

dynamic_competences = list(ALL_COMPETENCES)

def set_dynamic_competences(competences: list):
    global dynamic_competences
    if isinstance(competences, list) and len(competences) > 0:
        dynamic_competences = competences

def get_available_competences() -> list:
    return dynamic_competences if dynamic_competences else ALL_COMPETENCES
